trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  # azureSubscriptionEndpoint: sabaton-service-connection
  azureContainerRegistry: contoso.azurecr.io
  azureResourceGroup: sabaton-k8s-resources
  kubernetesCluster: sabaton-k8s


steps:
  - task: HelmInstaller@1
    displayName: Helm installer
    inputs: 
      helmVersionToInstall: latest

  - bash: |
      helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      helm repo add grafana https://grafana.github.io/helm-charts
      helm repo update

  - task: HelmDeploy@0
    displayName: Helm list installs
    inputs:
      connectionType: Azure Resource Manager
      # azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
      azureResourceGroup: $(azureResourceGroup)
      kubernetesCluster: $(kubernetesCluster)
      command: ls
      arguments: -all
  #
  - task: HelmDeploy@0
    displayName: Helm install prometheus
    inputs:
      connectionType: Azure Resource Manager
      # azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
      azureResourceGroup: $(azureResourceGroup)
      kubernetesCluster: $(kubernetesCluster)
      command: upgrade 
      releaseName: prometheus-community
      install: true
      chartName: prometheus-community/prometheus
      # useClusterAdmin: true
      namespace: monitoring

  - task: HelmDeploy@0
    displayName: Helm install grafana
    inputs:
      connectionType: Azure Resource Manager
      # azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
      azureResourceGroup: $(azureResourceGroup)
      kubernetesCluster: $(kubernetesCluster)
      command: upgrade 
      releaseName: grafana
      install: true
      chartName: grafana/grafana
      # useClusterAdmin: true
      namespace: monitoring
